config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }
  resources :destinations do
    resources :comments
    resources :reviews
  end
  resources :reviews 
  resources :tips
  get 'welcome/index'
  root 'welcome#index'
  get '/reviews/:id/review_data', to: 'reviews#review_data'
end

app/views/shared/_destination_review.html.erb
  <div class="row">
    <h1 class="show_headline">
      <%= @destination.name %>
    </h1>
  </div>
  <div class="row">

    <div class="col-lg-4">
      <h3 class="show_subheading">
        <strong>Region:</strong>
        <%= @destination.region %>
      </h3>

      <h3 class="show_subheading">
        <strong>Country:</strong>
        <%= @destination.country %>
      </h3>
      <%= link_to 'Add Review', new_destination_review_path(@destination), class: "btn btn-small btn-primary dest_button"%><br><br>
      <%= link_to "Edit Destination", edit_destination_path(@destination), class: "btn btn-info btn-xs dest_button" %><br><br>
      <% if current_user.admin? %>
      <%= link_to 'Delete Destination', [@destination], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning btn-xs dest_button" %><br><br>
      <% end %>
      <%= link_to "See all destinations", destinations_path, class: "btn btn-success btn-xs dest_button" %>
    </div>
  
    <div class="col-lg-4">
      <h3 class="show_subheading">Review</h3> 
      <% if @reviews.try(:any?) %>
      <% @reviews.take(1).each do |review| %>
        <h4 id="rating">Rating: <%= review.rating %></h4>
        
        <p id="reviewContent"><%= review.content %></p><br>

        <a href="#" class="js-previous btn btn-primary btn-xs" disabled data-id="<%=review.id%>" data-destination="<%= @destination.id %>">Previous Review</a>
       
        <a href="#" class="js-next btn btn-primary btn-xs" data-id="<%=review.id%>" data-destination="<%= @destination.id %>">Next Review</a><br><br>
        <% if review.user_id == current_user.id %>
        <%= link_to "Edit Review", edit_review_path(review), class: "btn btn-info btn-xs" %><br><br>
        <%= link_to 'Delete Review', destination_review_path(@destination, review), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning btn-xs" %><br><br>
        <% end %> 
      <% end %>
      <% end %>

    </div>

    <div class="col-lg-4">
       <h3 class="show_subheading">Comments</h3>
        
        <%= render 'comments/comments' %>
  
       <h4 class="comment_form">Add a comment:</h4>
      <%= render 'comments/form' %>
      <%= link_to "Load Comments", destination_comments_path(@destination, @comments), class: "loadComments btn btn-info btn-xs" %>
    </div>
  </div>

app/views/shared/_error_message.html.erb
  <% if object.errors.any? %>
    <div id="error_explanation" class="fields_with_errors">
      <h3>
        <%= pluralize(object.errors.count, "error") %> prohibited
        this from being saved:
      </h3>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>