config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }
  resources :destinations do
    resources :comments
    resources :reviews
  end
  resources :reviews 
  resources :tips
  get 'welcome/index'
  root 'welcome#index'
  get '/reviews/:id/review_data', to: 'reviews#review_data'
end

app/models/destination.rb
class Destination < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews

  validates :name, presence: true,
                   length: { minimum: 4 }
  validates :country, presence: true
  validates :region, presence: true
                     

  scope :alphabetically, -> { order("country ASC") }

  def reviews_attributes=(reviews_attributes)
    reviews_attributes.values.each do |review_attributes|
      self.reviews.build(review_attributes)
    end
  end

  def self.group_by_country
    alphabetically.group_by(&:country)
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_filter :find_destination, only: [:show, :edit, :update]

  def index
    @destinations = Destination.group_by_country
  end

  def show
    if !current_user
      redirect_to root_path, alert: "You must be logged in to continue."
    else
      @reviews = @destination.reviews
      @comments = @destination.comments
      @comment = @destination.comments.build
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @destination }
      end
    end
  end

  def new
    if !current_user
      redirect_to destinations_path, alert: "You must be logged in to add a destination"
    else
      @destination = Destination.new 
    end
  end

  def edit
    if current_user.admin?
    end
  end

  def create
    @destination = Destination.new(destination_params)
    @destination.reviews.first.user = current_user
    if @destination.save
      redirect_to @destination
    else
      render 'new'
    end
  end

  def update
      @destination.update(destination_params)
      redirect_to @destination, alert: "Only admin can edit destinations."
  end

  def destroy
    @destination = Destination.find(params[:id])
    if current_user.admin?
      @destination.destroy
    end
      redirect_to destinations_path, alert: "Only admin can delete destinations."
  end

  private

  def destination_params
    params.require(:destination).permit(:name, :region, :country, reviews_attributes: [:rating, :content, :user_id])
  end

  def find_destination
    @destination = Destination.find(params[:id])
  end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_dest_edit_form.html.erb
  <%= f.label :name %>
  <%= f.text_field :name, :class => "text_field"  %><br><br>
  
  <%= f.label :region %><br>  
    <%= f.radio_button :region, "North America" %>
    <%= f.label :region, "North America" %>

    <%= f.radio_button :region, "South America" %>
    <%= f.label :region, "South America" %>

    <%= f.radio_button :region, "Africa" %>
    <%= f.label :region, "Africa" %>

    <%= f.radio_button :region, "Europe" %>
    <%= f.label :region, "Europe" %>

    <%= f.radio_button :region, "Asia" %>
    <%= f.label :region, "Asia" %>

    <%= f.radio_button :region, "Australia" %>
    <%= f.label :region, "Australia" %>
    
  <br><br>
   
  <%= f.label :country %>
  <%= f.text_field :country, :class => "text_field" %><br><br>

app/views/destinations/_form.html.erb
<%= form_for @destination do |f| %>

  <%= render 'shared/error_message', object: @destination %>

  <%= f.label :name %>
  <%= f.text_field :name, :class => "text_field"  %><br><br>
  
  <%= f.label :region %><br>  
    <%= f.radio_button :region, "North America" %>
    <%= f.label :region, "North America" %>

    <%= f.radio_button :region, "South America" %>
    <%= f.label :region, "South America" %>

    <%= f.radio_button :region, "Africa" %>
    <%= f.label :region, "Africa" %>

    <%= f.radio_button :region, "Europe" %>
    <%= f.label :region, "Europe" %>

    <%= f.radio_button :region, "Asia" %>
    <%= f.label :region, "Asia" %>

    <%= f.radio_button :region, "Australia" %>
    <%= f.label :region, "Australia" %>
    
  <br><br>
   
  <%= f.label :country %>
  <%= f.text_field :country, :class => "text_field" %><br><br>
    
    <%= f.fields_for :reviews do |r| %>
   

    <%= render 'reviews/form_fields', f: r %>
    
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
 <% end %>
<% end %>

app/views/destinations/_new_form.html.erb
  <%= f.label :name %>
  <%= f.text_field :name, :class => "text_field"  %><br><br>
  
  <%= f.label :region %><br>  
    <%= f.radio_button :region, "North America" %>
    <%= f.label :region, "North America" %>

    <%= f.radio_button :region, "South America" %>
    <%= f.label :region, "South America" %>

    <%= f.radio_button :region, "Africa" %>
    <%= f.label :region, "Africa" %>

    <%= f.radio_button :region, "Europe" %>
    <%= f.label :region, "Europe" %>

    <%= f.radio_button :region, "Asia" %>
    <%= f.label :region, "Asia" %>

    <%= f.radio_button :region, "Australia" %>
    <%= f.label :region, "Australia" %>
    
  <br><br>
   
  <%= f.label :country %>
  <%= f.text_field :country, :class => "text_field" %><br><br>
    

app/views/destinations/edit.html.erb
<div class="container">
<%= form_for @destination do |f| %>

  <%= render 'shared/error_message', object: @destination %>

  <h1>Edit Destination</h1><br>
 

  <%= render 'dest_edit_form', f: f %><br>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %><br><br>
  </div>
 
  <%= link_to "See all destinations", destinations_path, class: "btn btn-success btn-lg" %>
<% end %>
</div>

app/views/destinations/index.html.erb
<div class="dest_index jumbotron">

  <h1>Destinations</h1>
  <h3>Find by country (alphabetically):</h3>
  <%= link_to 'Add New Destination', new_destination_path, class: "btn btn-lg btn-primary add_dest" %>

</div>

  <% @destinations.each do |country, destinations| %>
    <div>
      <p class="country"><%= country %></p>
      <% destinations.each do |destination| %>
      <p><%= link_to destination.name, destination_path(destination), class: "dest_name" %></p> 
    </div>  
     <% end %> 
  <% end %> 

app/views/destinations/new.html.erb
<div class="container">

<h1>New Destination</h1>

  <%= form_for @destination do |f| %>
    <%= render 'shared/error_message', object: @destination %>
    <%= render 'new_form', f: f %>
 
    <%= f.fields_for :reviews, @destination.reviews.build do |r| %>
  
    <%= render 'reviews/form', f: r %>
    
  <div class="actions">
    <%= f.submit "Add Destination", class: "btn btn-lg btn-primary" %>
  </div>
    <% end %>
  <% end %>
</div>

app/views/destinations/show.html.erb
<div class="container">

  <%= render 'shared/destination_review' %>
  
</div>