config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }
  resources :destinations do
    resources :comments
    resources :reviews
  end
  resources :reviews 
  resources :tips
  get 'welcome/index'
  root 'welcome#index'
  get '/reviews/:id/review_data', to: 'reviews#review_data'
end

app/models/tip.rb
class Tip < ActiveRecord::Base

  belongs_to :user

  validates :content, presence: true,
                      length: { minimum: 10 }
  validates :name, presence: true
  
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController

  def index
    @tips = Tip.all
  end

  def show
    @tip = Tip.find(params[:id])
  end

  def new
    if !current_user
      redirect_to tips_path, alert: "You must be logged in to add a travel tip"
    else
      @tip = Tip.new
    end
  end

  def edit
    @tip = Tip.find(params[:id])
    authorize @tip
  end

  def create
    @tip = Tip.new(tip_params)
    @tip.user = current_user

    if @tip.save
      redirect_to @tip
    else
      render 'new'
    end
  end

  def update
    @tip = Tip.find(params[:id])
    authorize @tip
    if @tip.user = current_user
      @tip.update(tip_params)
      redirect_to @tip
    else
      render 'edit', alert: "You can only edit your own tips"
    end
  end

  def destroy 
    @tip = Tip.find(params[:id])
    authorize @tip
    @tip.destroy
    redirect_to tips_path
   end

  private

  def tip_params
    params.require(:tip).permit(:name, :content, :user_id)
  end

end

app/views/tips/_form.html.erb
<%= form_for @tip do |f| %>

  <%= render 'shared/error_message', object: @tip %>

  <%= f.label :name %>
  <%= f.text_field :name, :class => "text_field"  %><br><br><br>
  
 
  <%= f.label :content %><br>
  <%= f.text_area :content, :class => "text_area"  %><br><br>


  <div class="actions">
    <%= f.submit "Add Travel Tip", class: "btn btn-lg btn-primary" %>
  </div>

<% end %>

app/views/tips/edit.html.erb
<div class="container">
  <h1>Edit Tip</h1><br>

  <%= render 'form' %><br>

  <%= link_to "See all Tips", tips_path, class: "btn btn-success btn-lg" %>
</div>

app/views/tips/index.html.erb
<div class="tips_index jumbotron">

  <h1>Travel Tips</h1>
  <h3>Get advice from fellow travelers to make your vacation as smooth as possible.</h3>

  <%= link_to 'New Travel Tip', new_tip_path, class: "btn btn-lg btn-primary add_dest" %>
</div>
<div class="container">
  <% @tips.each do |tip| %>
    <div>
      <p><%= link_to tip.name, tip_path(tip), class: "dest_name" %></p> 
    </div>
  <% end %>
</div>

app/views/tips/new.html.erb
<div class="container">

  <h1>Add Travel Tip</h1>

  <%= render '/tips/form' %>

</div>

app/views/tips/show.html.erb
<div class="tips_show jumbotron">
  <h1><%= @tip.name %></h1>
  <h3>by: <%= @tip.user.name %></h3>
</div>
<div class="container">
  <p><%= @tip.content %></p><br>
  <%= link_to "Edit Tip", edit_tip_path(@tip), class: "btn btn-info btn-small" %><br><br>
  <%= link_to 'Delete Tip', [@tip], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning btn-small" %><br><br>
  <%= link_to "See all tips", tips_path, class: "btn btn-success btn-small" %>
</div>