config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }
  resources :destinations do
    resources :comments
    resources :reviews
  end
  resources :reviews 
  resources :tips
  get 'welcome/index'
  root 'welcome#index'
  get '/reviews/:id/review_data', to: 'reviews#review_data'
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; Globetrotters 2016</p>
</div>

app/views/layouts/_navigation.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Globetrotters", welcome_index_path, class: "nav-brand", id: "logo" %>
      <div class="nav_item">
        <%= link_to "Destinations", destinations_path, class: "navbar_links" %>
        <%= link_to "Reviews", reviews_path, class: "navbar_links" %>
        <%= link_to "Tips", tips_path, class: "navbar_links" %>
        
        <% if !user_signed_in? %>
          <%= link_to 'Signup', new_user_registration_path, class: "btn btn-lg btn-success", id: "signup" %> 
          <%= link_to 'Login', user_session_path, class: "btn btn-lg btn-info", id: "login" %> 
          <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class: "btn btn-lg btn-primary", id: "facebook_login" %>
        <% else %>
          <p class="user_greeting">Hello <%= current_user.name %>!</p>
          <%= link_to 'Log Out', destroy_user_session_path,  :method => :delete, class: "btn btn-lg btn-warning", id: "logout" %> 
        <% end %>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Globetrotters</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
 
  <%= csrf_meta_tags %>

</head>
<body>

  <%= render 'layouts/navigation' %>
    <%- flash.each do |name, msg| -%>
      <h3><%= content_tag :div, msg, :class => "error_explanation" if msg.is_a?(String) %></h3>
    <%- end -%> 

  <%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>